[test] [bug-fix] Tests could run out of file desciptors
h2o/h2o pull request #2908
Opened 2021-12-17 00:05 UTC by nalramli

Depending on the system configuration, `h2o` could run out of file descriptors on start up while running tests in docker on a machine with a large number of cores.

2021-12-17 00:39 UTC, gfx commented
I think it would be better if we'll add `--ulimit` to docker options directly: https://github.com/h2o/h2o/blob/master/misc/docker-ci/check.mk#L9

2021-12-17 03:30 UTC, nalramli commented
I have tried that but it doesn't work.  I also tried setting `limits.conf` and several other methods but by the time the execution reaches the test script the `nofiles` limit is set back to `1024` in my environment.  This is the only way I could find to fix it.

2021-12-17 04:41 UTC, kazuho requested changes
I'm not sure if this is the correct fix for the symptom.

prlimit controls number of files that can be opened by one process. Therefore, it would make sense to use prlimit only if the symptom is unrelated to the test concurrency.

If the symptom is related to test concurrency, I believe that the number of file descriptors should be adjusted at the system level (e.g., docker, host environment).

Regarding the number of file descriptors that we need for each test, my belief is that 1024 is sufficient; in fact, we intentionally limit that to 1024, see https://github.com/h2o/h2o/pull/2887/commits/71b96467808aeb7212c0e4ce6b9ce6ac52a95517. This is necessary to run tests quickly. When h2o launches using neverbleed, neverbleed has to close all file descriptors. But if the `RLIMIT_NOFILE` is set to a high value, it takes looong time.

2021-12-17 04:57 UTC, nalramli commented
@kazuho 

The symptom is sort of unrelated to the test concurrency in that `h2o` fails to start up when the system has a large number of CPU cores but `prlimit` is small and `num-threads` is not specified, exiting at [h2o/h2o/src/main.c@6322014e#L3732](https://github.com/h2o/h2o/blob/6322014e98ee4881dbaaf131c22d5450fc75b572/src/main.c#L3732).

As I mentioned earlier, I have tried to set it at the system level (in docker, on the host, in the container, even in CMake), nothing worked.  So the other options I can think of is to pass `num-threads` into the test configurations or to modify the relevant `h2o` code.

I agree that 1024 FDs is sufficient.  However if `num-threads` is not specified, as is the case with many of the unit tests, then `h2o` will launch as many threads as there are CPU cores, so if your trying to run the unit tests on a machine with a high number of CPU cores but a small `nofiles` limit then the unit tests will fail.

2021-12-17 05:10 UTC, kazuho commented
@nalramli Thank you for the clarification. I can probably see that some tests (or h2o) might require more file descriptors when there are many cores available. To give an example, to handle QUIC traffic, h2o opens one UDP port per worker thread. Though unless you have many many cores, I do not think that would cause the tests to start failing.

OTOH, I'm not sure if I follow this logic:
> The symptom is sort of unrelated to the test concurrency in that `h2o` fails to start up when the system has a large number of CPU cores but `prlimit` is small and `num-threads` is not specified, exiting at h2o/h2o/src/main.c@6322014e#L3732.

The code here compares two variables max-connections and RLIMIT_NO_FILE, which are both 1024 by default. I do not think either of them would change depending on the numbers of CPU cores.

2021-12-18 00:27 UTC, nalramli commented
Thanks for your review, per our offline discussion, I have updated it to set `num-threads` instead of `nofiles` in c78e188.

2021-12-19 02:38 UTC, merged

2021-12-19 02:39 UTC, kazuho commented
Thank you for he changes. Merged with 2cad0b3 to address failures introduced by adding `num-threads: 2`.